name: build

on: 
  push:
    branches: 
      - main

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
      - name: Login to GitHub Container REGISTRY
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Sanitize repo slug
        uses: actions/github-script@v4
        id: repo_slug
        with:
          result-encoding: string
          script: return '${{ github.repository }}'.toLowerCase()
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ steps.repo_slug.outputs.result }}:latest
